# Generated by Django 5.1.1 on 2024-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
